Aligned package codebase with eZ Platform v2.5 requirements
ezsystems/ezplatform-design-engine pull request #30
Opened 2021-04-13 15:45 UTC by alongosz

| Question                                  | Answer
| ---------------------------------------- | ------------------
| **JIRA issue**                          | n/a
| **Type**                                   | bug
| **Target eZ Platform version** | `v2.5`+
| **BC breaks**                          | yes

Looks like we have misaligned Composer & CS configuration for eZ Platform Design Engine. Branch 2.0 was meant to support eZ Platform v2.x only, Symfony 3.4+, and Twig 2.0.

Branch 2.0 is not tested during nightly builds, so the issues were not visible.

#### TODO
- [ ] Fix PR template on merge up

#### Checklist:
- [x] Provided PR description.
- [x] Tested the solution manually.
- [x] Checked that target branch is set correctly (master for features, the oldest supported for bugs).
- [x] Ran PHP CS Fixer for new PHP code (use `$ composer fix-cs`).
- [x] Asked for a review

2021-04-14 06:38 UTC, mnocon requested changes
Travis fails with:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1

    - Root composer.json requires twig/twig ^2.14.4 -> satisfiable by twig/twig[v2.14.4].

    - twig/twig v2.14.4 requires php >=7.2.5 -> your php version (7.1.27) does not satisfy that requirement.

  Problem 2

    - twig/twig v2.14.4 requires php >=7.2.5 -> your php version (7.1.27) does not satisfy that requirement.

    - symfony/symfony v3.4.47 requires twig/twig ^1.41|^2.10 -> satisfiable by twig/twig[v2.14.4].

    - Root composer.json requires symfony/symfony ^3.4.47 -> satisfiable by symfony/symfony[v3.4.47].
 ```

Looks like we need to make the dependencies compatible with PHP 7.1 (the lowest supported for eZ Platform 2.5)

2021-04-14 11:22 UTC, alongosz commented
@mnocon fixed the issue. Since eZ Platform 2.5 supports PHP 7.1, we should have here at most `twig/twig:^2.13.1`.

2021-04-19 09:17 UTC, mnocon approved these changes

2021-05-10 06:44 UTC, adamwojs approved these changes

2022-07-15 13:09 UTC, alongosz commented
eZ Platform 2.5 is past EOM. AFAICS issues shared by higher versions were either already ported or resolved in a different way. Closing as obsolete.

2022-07-15 13:09 UTC, closed without merging